name: TET Tests

on:
  push:
    branches:
      - main  # Adjust this branch to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest  # You can change the runner to your preferred OS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install TET
      run: |
        git clone https://github.com/linux-test-project/ltp.git
        cd ltp
        make autotools
        ./configure
        make

    - name: Run TET Tests
      run: |
        cd ltp
        make -C testcases
        ./testcases/runtest

